### ISSUE TITLE
Cannot use model `o3-mini`

### ISSUE THREAD

**Issue by sora32127** [qodo-ai/pr-agent#1511]
### Git provider

Github Cloud

### System Info

model used: o3-mini
deployment: GitHub Actions
Provider: Azure OpenAI Service

### Bug details

# Summary
When using the o3-mini model in GitHub Actions with Qodo Merge, I encountered an error in the response.

# Goal
To successfully integrate and use the o3-mini model in my workflow.

# Steps to Reproduce

1. Configure Qodo Merge in GitHub Actions using the following YAML configuration:

```yaml
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI.API_TYPE: 'azure'
          OPENAI.API_VERSION: '2024-12-01-preview'
          OPENAI.KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          OPENAI.API_BASE: ${{ secrets.AZURE_OPENAI_API_BASE }}
          OPENAI.DEPLOYMENT_ID: 'o3-mini'
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: 'answer in Japanese'
          PR_REVIEWER.EXTRA_INSTRUCTIONS: 'answer in Japanese'
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: 'answer in Japanese'
```

2. Configure the model in Azure OpenAI Service and obtain the API Key, API_BASE, and DEPLOYMENT_ID

3. Create a PR and monitor the `Actions` tab

# Error Log
The following error appears in GitHub Actions:

> {"text": "Error during LLM inference: litellm.BadRequestError: AzureException BadRequestError - Unsupported parameter: 'temperature' is not supported with this model.\n", "record": {"elapsed": {"repr": "0:02:08.769192", "seconds": 128.769192}, "exception": null, "extra": {}, "file": {"name": "litellm_ai_handler.py", "path": "/app/pr_agent/algo/ai_handlers/litellm_ai_handler.py"}, "function": "chat_completion", "level": {"icon": ":警告:", "name": "WARNING", "no": 30}, "line": 248, "message": "Error during LLM inference: litellm.BadRequestError: AzureException BadRequestError - Unsupported parameter: 'temperature' is not supported with this model.", "module": "litellm_ai_handler", "name": "pr_agent.algo.ai_handlers.litellm_ai_handler", "process": {"id": 6, "name": "MainProcess"}, "thread": {"id": 139684855106432, "name": "MainThread"}, "time": {"repr": "2025-02-03 02:30:13.166003+00:00", "timestamp": 1738549813.166003}}}

**Comment by mrT23** [comment]
try running from CLI, and see what went wrong.

with 'o3-mini', you should go here, where there is not temperature:
https://github.com/qodo-ai/pr-agent/blob/24bf875db6cb7f3ef6c8d8add1d7f8f4f70ed5cf/pr_agent/algo/ai_handlers/litellm_ai_handler.py#L206

(https://github.com/qodo-ai/pr-agent/blob/main/pr_agent/algo/__init__.py#L93)

**Comment by sora32127** [comment]
@mrT23

Thank you for your quick response.

I have confirmed that Qodo Merge functions correctly when using CLI commands, but fails during PR creation.

I tested the functionality using CLI commands:
1. Executed the `/describe` command in a PR comment
2. Qodo Merge successfully updated the PR description as expected

![Successful CLI Command Execution](https://github.com/user-attachments/assets/bc546ff2-0420-4068-b446-1a0080bc2d7c)

However, Qodo Merge fails to function when creating a new PR.

**Comment by mrT23** [comment]
so validate your configurations for github action.
They should match the configurations you give in CLI.
If they do, no reason it should behave differently


![Image](https://github.com/user-attachments/assets/411c584d-7a61-4a7f-9f58-e1ce823f7644)

I don't see here anywhere `config.model`, `config.fallback_models`, for example

**Comment by sora32127** [comment]
@mrT23

Thank you for your support.

## Resolution Update
I have successfully resolved the issue by adding `CONFIG.MODEL` to the workflow configuration. Now:
- Qodo Merge automatically generates descriptions and suggestions as expected
- All slash commands are functioning properly

Below is the working configuration:
 
```yaml
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI.API_TYPE: 'azure'
          OPENAI.API_VERSION: '2024-12-01-preview'
          OPENAI.KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          OPENAI.API_BASE: ${{ secrets.AZURE_OPENAI_API_BASE }}
          OPENAI.DEPLOYMENT_ID: 'o3-mini'
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: 'answer in Japanese'
          PR_REVIEWER.EXTRA_INSTRUCTIONS: 'answer in Japanese'
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: 'answer in Japanese'
          CONFIG.MODEL: 'o3-mini'
```

Thank you for maintaining this excellent OSS project!
