### ISSUE TITLE
Cannot Call Azure OpenAI from Azure DevOps

### ISSUE THREAD

**Issue by skdmstg-github** [qodo-ai/pr-agent#1520]
### Git provider (optional)

Azure

### System Info (optional)

- Model: Azure OpenAI, GPT4o
- Git provider: Azure
- Actions: Azure DevOps (pipeline)

### Issues details

I want to use Azure OpenAI to review PRs (Pull Requests) created in Azure DevOps. I am using the pipeline in Azure DevOps.
I implemented it according to the installation, but when I trigger the pipeline, I get the following error.

2025-02-05 08:10:03.785 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:248 - Error during LLM inference: litellm.AuthenticationError: AuthenticationError: OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect API key provided: ************************************************************************************. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

```
# Opt out of CI triggers
trigger: none

# Configure PR trigger
pr:
  branches:
    include:
    - '*'
  autoCancel: true
  drafts: false

stages:
- stage: pr_agent
  displayName: 'PR Agent Stage'
  jobs:
  - job: pr_agent_job
    displayName: 'PR Agent Job'
    pool:
      vmImage: 'ubuntu-latest'
    container:
      image: codiumai/pr-agent:latest
      options: --entrypoint ""
    variables:
      - group: pr_agent
    steps:
    - script: |
        echo "Running PR Agent action step"

        # Construct PR_URL
        PR_URL="${SYSTEM_COLLECTIONURI}${SYSTEM_TEAMPROJECT}/_git/${BUILD_REPOSITORY_NAME}/pullrequest/${SYSTEM_PULLREQUEST_PULLREQUESTID}"
        echo "PR_URL=$PR_URL"

        # Extract organization URL from System.CollectionUri
        ORG_URL=$(echo "$(System.CollectionUri)" | sed 's/\/$//') # Remove trailing slash if present
        echo "Organization URL: $ORG_URL"

        export azure_devops__org="$ORG_URL"
        export config__git_provider="azure"

        pr-agent --pr_url="$PR_URL" describe
        pr-agent --pr_url="$PR_URL" review
        pr-agent --pr_url="$PR_URL" improve
      env:
        azure_devops__pat: $(azure_devops_pat)
        openai__key: $(OPENAI_KEY)
      displayName: 'Run Qodo Merge'
```
The variables are saved in the Library, and the calls are successful.

Do you know the cause and solution?

**Comment by mrT23** [comment]
https://qodo-merge-docs.qodo.ai/usage-guide/changing_a_model/#azure
Give the needed params. 

I dont know exactly what the problem is with your local deployment, but the core issue is almost always the same  - missing\bad params (see [here](https://github.com/qodo-ai/pr-agent/issues/1511) for example)

**Comment by skdmstg-github** [comment]
I'm sorry for the delay, but by setting the parameters correctly, it started working. Thank you. Also, I’ll leave a sample of the parameters here for others who are facing the same issue.
```
      env:
        AZURE_DEVOPS.PAT: $(azure_devops_pat)
        OPENAI.API_TYPE: 'azure'
        OPENAI.KEY: $(OPENAI_KEY)
        OPENAI.API_BASE: $(AZURE_OPENAI_ENDPOINT)
        PR_DESCRIPTION.EXTRA_INSTRUCTIONS: 'use only japanese'
        PR_REVIEWER.EXTRA_INSTRUCTIONS: 'use only japanese'
        PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: 'use only japanese'
        CONFIG.MODEL: $(AZURE_OPENAI_DEPLOYMENT_NAME)
```
