### ISSUE TITLE
review and improve Tool Errors

### ISSUE THREAD

**Issue by rsys-cmaheswa** [qodo-ai/pr-agent#1524]
### Git provider (optional)

Bitbucket Server

### System Info (optional)

System Configuration:

Model Used:

**Model: ollama/ollama/gemma:7b**

Running on GPU:
NVIDIA-SMI Version: 565.57.01
Driver Version: 565.57.01
CUDA Version: 12.7
Tool:

PR-Agent (CLI) we are using 
Configuration Details:

Configuration File: configuration.toml
**git_provider = "bitbucket_server"**

Secrets File: .secrets.toml

**[config]
model = "ollama/llama3.1:8b"
fallback_models = ["ollama/llama3.1:8b"]
custom_model_max_tokens = 128000 # Maximal input tokens for the model
duplicate_examples = true # Duplicate examples in the prompt for structured output

[ollama]
api_base = "my ollama server endpoint" # Specify your Ollama server endpoint and port

[bitbucket_server]
bearer_token  = "our bitbucker server barier token"

### Issues details

The following tools are working:

1)ask
2)add_docs
3)update_changelog
4)describe
The following tools are not working:

1)improve
2)review

 **Improve tool getting following err:**
2025-02-10 19:03:10.510 | INFO     | pr_agent.algo.utils:try_fix_yaml:778 - Successfully parsed AI prediction after extracting yaml snippet
2025-02-10 19:03:10.510 | ERROR    | pr_agent.algo.utils:load_yaml:710 - Failed to parse AI prediction after fallbacks
2025-02-10 19:03:10.514 | WARNING  | pr_agent.algo.pr_processing:retry_with_fallback_models:350 - Failed to generate prediction with ollama/llama3.1:8b
2025-02-10 19:03:10.516 | ERROR    | pr_agent.tools.pr_code_suggestions:run:191 - Failed to generate code suggestions for PR, error: Failed to generate prediction with any model of ['ollama/gemma:7b', 'ollama/llama3.1:8b']

**Review tool throwing Following err:**

2025-02-10 19:03:57.519 | WARNING  | pr_agent.algo.utils:load_yaml:707 - Initial failure to parse AI prediction: while scanning for the next token
found character '`' that cannot start any token
  in "<unicode string>", line 18, column 29:
        - added two new models: `Criteria` and `CustomView`.
                                ^
2025-02-10 19:03:57.521 | INFO     | pr_agent.algo.utils:try_fix_yaml:778 - Successfully parsed AI prediction after extracting yaml snippet
2025-02-10 19:03:57.521 | INFO     | pr_agent.algo.utils:load_yaml:713 - Successfully parsed AI prediction after fallbacks
2025-02-10 19:03:57.521 | ERROR    | pr_agent.tools.pr_reviewer:run:176 - Failed to review PR: string indices must be integers, not 'str'

Is it a model problem or something we're missing? We only made changes to the configuration.yaml and .secrets.toml files.

**Comment by syahidfrd** [comment]
i have same issue with gemini 1.5 flash model

**Comment by mrT23** [comment]
https://qodo-merge-docs.qodo.ai/usage-guide/changing_a_model/#ollama

![Image](https://github.com/user-attachments/assets/ccd142bd-9c22-4ae2-9e64-19068cb6e1cf)

Try the 'ask' command. it will work probably.

But for more elaborate commands, you will need far better models

**Comment by rsys-cmaheswa** [comment]
Can I bypass AI prediction and upload whatever AI Response got from Model? 
So that at least improve, and review tool output will add in bitbucket

**Comment by mrT23** [comment]
No, it is not supported

**Comment by rsys-cmaheswa** [comment]
Oh, Ok Thanks @mrT23

**Comment by alessio-locatelli** [comment]
## Preface

@mrT23  I see [quite a lot of issues about YAML parsing](https://github.com/search?q=repo%3Aqodo-ai%2Fpr-agent+%22Failed+to+parse+AI+prediction%22&type=issues), and I have a clear and straightforward fix that can make YAML code great again. I want to discuss whether I am moving in the right direction. 

#### :x: In the following example, the `issue_content` contains special characters (``` ` ``` and `:`), and the field value is unquoted. 

```yaml
review:
  key_issues_to_review:
    - relevant_file: example.yaml
      issue_header: Configuration Check
      issue_content: Verify that the `foobar-spameggs` Kubernetes secret exists in the target environment and contains the necessary keys: `foobar-spameggs-host`, `foobar-spameggs-port`, and `foobar-spameggs-password`.
      start_line: 79
      end_line: 93
```


This Stack Overflow discussion has good explanations: https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml, as does this tutorial: https://www.yaml.info/learn/quote.html.

#### ✅  The correct YAML must use single or double quotes around the value.

```yaml
review:
  key_issues_to_review:
    - relevant_file: example.yaml
      issue_header: Configuration Check
      issue_content: "Verify that the `foobar-spameggs` Kubernetes secret exists in the target environment and contains the necessary keys: `foobar-spameggs-host`, `foobar-spameggs-port`, and `foobar-spameggs-password`."
      start_line: 79
      end_line: 93
```

## 🐛 Current `pr-agent` behavior 

```sh
``yaml
review:
  key_issues_to_review:
    - relevant_file: example.yaml
      issue_header: Configuration Check
      issue_content: "Verify that the `foobar-spameggs` Kubernetes secret exists in the target environment and contains the necessary keys: `foobar-spameggs-host`, `foobar-spameggs-port`, and `foobar-spameggs-password`."
      start_line: 79
      end_line: 93
``
2025-06-17 13:47:40.843 | WARNING  | pr_agent.algo.utils:load_yaml:714 - Initial failure to parse AI prediction: mapping values are not allowed here
  in "<unicode string>", line 8, column 137:
     ...  and contains the necessary keys: `foobar-spameggs--host`, `foobar- ... 
                                         ^
2025-06-17 13:47:40.855 | ERROR    | pr_agent.algo.utils:load_yaml:718 - Failed to parse AI prediction after fallbacks
2025-06-17 13:47:40.857 | ERROR    | pr_agent.tools.pr_reviewer:run:182 - Failed to review PR: argument of type 'NoneType' is not iterable
```


## What to do

If possible, I would like to clarify: Was quoting already suggested by someone but rejected for some reason? I do not want to duplicate work that was already done, but rejected.

If I am moving in the right direction, there will be two points to investigate:
1. Who must add quotes: ask the AI to add the quotes around the `issue_content` field or inject the quotes on our side before we parse YAML?
2. Single versus double quotes around the `issue_content` field.
