### ISSUE TITLE
no need temperature for o3-mini

### ISSUE THREAD

**Issue by watarukura** [qodo-ai/pr-agent#1540]
### Git provider

Github Cloud

### System Info

My github actions workflow is here.

```yaml
      - name: PR Agent action step
        id: pragent
        if: github.event.pull_request.user.login != 'renovate[bot]'
        uses: qodo-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          OPENAI.API_TYPE: "azure"
          OPENAI_API_VERSION: "2024-12-01-preview"
          AZURE_API_VERSION: "2024-12-01-preview"
          OPENAI.API_BASE: ${{ secrets.OPENAI_API_BASE }}
          OPENAI.DEPLOYMENT_ID: ${{ secrets.OPENAI_API_DEPLOYMENT_ID }}
          CONFIG.MODEL: "o3-mini-2025-01-31"
          PR_REVIEWER.REQUIRE_FOCUSED_REVIEW: "false"
          PR_REVIEWER.REQUIRE_SCORE_REVIEW: "false"
          PR_REVIEWER.REQUIRE_TESTS_REVIEW: "false"
          PR_REVIEWER.REQUIRE_SECURITY_REVIEW: "false"
          PR_REVIEWER.REQUIRE_ESTIMATE_EFFORT_TO_REVIEW: "true"
          PR_REVIEWER.EXTRA_INSTRUCTIONS: "Provide all responses in Japanese. Use natural and professional Japanese."
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: "Provide all responses in Japanese. Use natural and professional Japanese."
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: "Provide all responses in Japanese. Use natural and professional Japanese."
          PR_ADD_DOCS.EXTRA_INSTRUCTIONS: "Provide all responses in Japanese. Use natural and professional Japanese."
          PR_UPDATE_CHANGELOG.EXTRA_INSTRUCTIONS: "Provide all responses in Japanese. Use natural and professional Japanese."
          GITHUB_ACTION.AUTO_REVIEW: "true"
          GITHUB_ACTION_CONFIG.PR_ACTIONS: '["opened", "reopened", "ready_for_review", "review_requested", "synchronize"]'
```

And, Build qodo-ai/pr-agent step's log is here.

```text
  #0 building with "default" instance using docker driver
  
  #1 [internal] load build definition from Dockerfile.github_action_dockerhub
  #1 transferring dockerfile: 98B done
  #1 DONE 0.0s
  
  #2 [auth] codiumai/pr-agent:pull token for registry-1.docker.io
  #2 DONE 0.0s
  
  #3 [internal] load metadata for docker.io/codiumai/pr-agent:github_action
  #3 DONE 0.4s
  
  #4 [internal] load .dockerignore
  #4 transferring context: 110B done
  #4 DONE 0.0s
  
  #5 [1/1] FROM docker.io/codiumai/pr-agent:github_action@sha256:5de048fe55ac571455470d38d975f536a7cafcf97b746bb344a21cf0ade6cbd6
  #5 resolve docker.io/codiumai/pr-agent:github_action@sha256:5de048fe55ac571455470d38d975f536a7cafcf97b746bb344a21cf0ade6cbd6 done
...
```

I think pr-agent:github_action@sha256:5de048f includes https://github.com/qodo-ai/pr-agent/pull/1537, but use `o3-mini` and call Azure OpenAI Service with `temperature`.

### Bug details

```json
{"text": "Error during LLM inference: litellm.BadRequestError: AzureException BadRequestError - Unsupported parameter: 'temperature' is not supported with this model.\n", "record": {"elapsed": {"repr": "0:00:04.603525", "seconds": 4.603525}, "exception": null, "extra": {}, "file": {"name": "litellm_ai_handler.py", "path": "/app/pr_agent/algo/ai_handlers/litellm_ai_handler.py"}, "function": "chat_completion", "level": {"icon": "⚠️", "name": "WARNING", "no": 30}, "line": 254, "message": "Error during LLM inference: litellm.BadRequestError: AzureException BadRequestError - Unsupported parameter: 'temperature' is not supported with this model.", "module": "litellm_ai_handler", "name": "pr_agent.algo.ai_handlers.litellm_ai_handler", "process": {"id": 7, "name": "MainProcess"}, "thread": {"id": 139929154456448, "name": "MainThread"}, "time": {"repr": "2025-02-17 04:43:48.073720+00:00", "timestamp": 1739767428.07372}}}
```
