### ISSUE TITLE
Support Dunder instead of Dot for Env Variables

### ISSUE THREAD

**Issue by nicohein** [qodo-ai/pr-agent#1695]
### Feature request

PR-Agent currently relies on env variables with a Dot in their names like `CONFIG.GIT_PROVIDER`. This is a little unusual and e.g. requires the Docker in Docker BitBucket pipeline setup as the example given here: https://qodo-merge-docs.qodo.ai/installation/bitbucket/

```yaml
pipelines:
  pull-requests:
    "**":
      - step:
          name: PR Agent Review
          image: python:3.12
          services:
            - docker
          script:
            - docker run -e CONFIG.GIT_PROVIDER=bitbucket -e OPENAI.KEY=$OPENAI_API_KEY -e BITBUCKET.BEARER_TOKEN=$BITBUCKET_BEARER_TOKEN codiumai/pr-agent:latest --pr_url=https://bitbucket.org/$BITBUCKET_WORKSPACE/$BITBUCKET_REPO_SLUG/pull-requests/$BITBUCKET_PR_ID review
```

if PR-Agent would support Double Underscores likes `CONFIG__GIT_PROVIDER` then this could be simply rewritten as 

```yaml
pipelines:
    pull-requests:
      '**':
        - step:
            name: PR Agent Review
            image: codiumai/pr-agent:latest
            script:
              - pr-agent --pr_url=https://bitbucket.org/$BITBUCKET_WORKSPACE/$BITBUCKET_REPO_SLUG/pull-requests/$BITBUCKET_PR_ID review
```

In fact, this was supported (but undocumented) until version 0.27, and I would love to have the support back.

### Motivation

A simplified setup for environments that do not support dots `.` inside of environment variables.
