### ISSUE TITLE
How to use the qwen model in the tool

### ISSUE THREAD

**Issue by 947776795** [qodo-ai/pr-agent#1714]
### Feature request

The project uses LiteLLM and currently cannot call the qwen model. 
I hope there is a good way to use the qwen model. 
I hope to get help

### Motivation

In China, qwen is a popular model

**Comment by HRXWEB** [comment]
@947776795 

Qwen 在[百炼平台](https://bailian.console.aliyun.com/?spm=5176.29597918.J_bNSze_09Z5SDm7ZHdpz3Y.1.2f197ca0K1bkPL&tab=api#/api/?type=model&url=https%3A%2F%2Fhelp.aliyun.com%2Fdocument_detail%2F2712576.html&renderType=iframe)的 API 是 OpenAI 兼容的，直接在 `.secrets.toml` 配置 \[openai\] 部分的 key 和 api_base 就行了.

ps: 我没有尝试过，但是理论上是完全可行的。

**Comment by Faithree** [comment]
I also encountered a similar problem
1. I didn't see where to set the base_url in the custom model
2. A third-party model transfer platform compatible with open ai. I can't see where to set the base_url

**Comment by naorpeled** [comment]
Qwen works today, no code change needed. DashScope (Aliyun) exposes an OpenAI-compatible endpoint, so you route it through the `[openai]` section. The confirmed-working setup from this thread (thanks @EjiHuang):

```toml
# .secrets.toml
[openai]
key = "sk-xxx"                                               # your DashScope key
api_base = "https://dashscope.aliyuncs.com/compatible-mode/v1"

# configuration.toml
[config]
model = "dashscope/qwen3-max"        # or qwen2.5-coder, etc.
fallback_models = ["qwen3-max"]
custom_model_max_tokens = 32000      # required, see below
```

To answer the recurring question about where the key and base_url go (@djaffer @Faithree): it's `key` and `api_base` under `[openai]` in `.secrets.toml`, or the env vars `OPENAI__KEY` / `OPENAI__API_BASE` (double underscore). PR-Agent feeds that `api_base` to every LiteLLM call, so any OpenAI-compatible endpoint works the same way.

`custom_model_max_tokens` is the part people miss: Qwen models aren't in PR-Agent's built-in token table, so without it you'll hit a "model not defined in MAX_TOKENS" error. Set it to the model's context size.

If you'd rather run Qwen locally via Ollama instead:

```toml
[config]
model = "ollama/qwen2.5-coder:32b"
custom_model_max_tokens = 128000
[ollama]
api_base = "http://localhost:11434"
```

Docs: https://github.com/the-pr-agent/pr-agent/blob/main/docs/docs/usage-guide/changing_a_model.md

Closing as answered, reopen if you hit a snag with a specific Qwen model.
