### ISSUE TITLE
Add Gemini models for pr agent in github actions

### ISSUE THREAD

**Issue by Yash-1511** [qodo-ai/pr-agent#1729]
### Git provider (optional)

Github Cloud

### Issues details

```
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GOOGLE_AI_STUDIO_GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
            PR_AGENT_MODEL: "google_ai_studio/gemini-2.5-flash"
```

is this configuration right. pr agent is not generating the review.  i am using github.
