### ISSUE TITLE
Having trouble switching to Gemini

### ISSUE THREAD

**Issue by dep** [qodo-ai/pr-agent#1734]
### Git provider (optional)

None

### Issues details

Here's my configuration:

```yml
- name: PR Agent action step
  continue-on-error: true
  id: pragent
  uses: qodo-ai/pr-agent@main
  env:
    model: "gemini/gemini-2.0-flash"
    # note I've tried both of the below, same result:
    GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    GOOGLE_AI_STUDIO.GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    GITHUB_TOKEN: ${{ secrets.TITAN_PACKAGE_MANAGER_TOKEN }}
    github_action.auto_review: "false"
    github_action.auto_describe: "true"
    github_action.auto_improve: "false"
    pr_description.use_description_markers: "true"
    pr_reviewer.ask_and_reflect: "true"
    pr_description.enable_file_walkthrough: "false"
    pr_description.keep_original_user_title: "true"
    pr_description.add_original_user_description: "true"
    pr_code_suggestions.num_code_suggestions: 0
    pr_code_suggestions.summarize: "false"
    pr_code_suggestions.rank_suggestions: "true"
```

Action step logging:

```
Run qodo-ai/pr-agent@main
/usr/bin/docker run --name f35eb155f14c49974515bb621325b4878130_2bcb86 --label 01f35e --workdir /github/workspace --rm -e "model" -e "GEMINI_API_KEY" -e "GOOGLE_AI_STUDIO.GEMINI_API_KEY" -e "GITHUB_TOKEN" -e "github_action.auto_review" -e "github_action.auto_describe" -e "github_action.auto_improve" -e "pr_description.use_description_markers" -e "pr_reviewer.ask_and_reflect" -e "pr_description.enable_file_walkthrough" -e "pr_description.keep_original_user_title" -e "pr_description.add_original_user_description" -e "pr_code_suggestions.num_code_suggestions" -e "pr_code_suggestions.summarize" -e "pr_code_suggestions.rank_suggestions" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e
OPENAI_KEY not set
{"text": "Applying repo settings\n", "record": {"elapsed": {"repr": "0:00:02.[18](https://github.com/Invoca/Titan/actions/runs/14755056770/job/41421188204?pr=4894#step:3:19)6447", "seconds": 2.186447}, "exception": null, "extra": {}, "file": {"name": "github_action_runner.py", "path": "/app/pr_agent/servers/github_action_runner.py"}, "function": "run_action", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 75, "message": "Applying repo settings", "module": "github_action_runner", "name": "__main__", "process": {"id": 7, "name": "MainProcess"}, "thread": {"id": 140347992587136, "name": "MainThread"}, "time": {"repr": "2025-04-30 13:00:16.764338+00:00", "timestamp": 1746018016.764338}}}
{"text": "enable_custom_labels: False\n", "record": {"elapsed": {"repr": "0:00:03.337397", "seconds": 3.337397}, "exception": null, "extra": {}, "file": {"name": "github_action_runner.py", "path": "/app/pr_agent/servers/github_action_runner.py"}, "function": "run_action", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 79, "message": "enable_custom_labels: False", "module": "github_action_runner", "name": "__main__", "process": {"id": 7, "name": "MainProcess"}, "thread": {"id": 140347992587136, "name": "MainThread"}, "time": {"repr": "[20](https://github.com/Invoca/Titan/actions/runs/14755056770/job/41421188204?pr=4894#step:3:21)25-04-30 13:00:17.915288+00:00", "timestamp": 1746018017.915288}}}
{"text": "Skipping action: synchronize\n", "record": {"elapsed": {"repr": "0:00:03.337965", "seconds": 3.337965}, "exception": null, "extra": {}, "file": {"name": "github_action_runner.py", "path": "/app/pr_agent/servers/github_action_runner.py"}, "function": "run_action", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 117, "message": "Skipping action: synchronize", "module": "github_action_runner", "name": "__main__", "process": {"id": 7, "name": "MainProcess"}, "thread": {"id": 140347992587136, "name": "MainThread"}, "time": {"repr": "2025-04-30 13:00:17.915856+00:00", "timestamp": 1746018017.915856}}}
```

**Comment by gardner** [comment]
>   env:
>     model: "google_ai_studio/gemini-2.0-flash"
>     GOOGLE_AI_STUDIO__GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}


It looks like the `model:` part of this bot response is contrary to what is in the documentation. The environment variable is correct at least: https://qodo-merge-docs.qodo.ai/usage-guide/changing_a_model/#vertex-ai

**Comment by LeonManolo** [comment]
This is working for me (you have to close and reopen the PR for it to work):

```
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          CONFIG__MODEL: "gemini/gemini-2.0-flash" # not "MODEL" !
          GOOGLE_AI_STUDIO__GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
