### ISSUE TITLE
How do you specify the model in configuration file?

### ISSUE THREAD

**Issue by MakotoE** [qodo-ai/pr-agent#1800]
### Git provider (optional)

Github Cloud

### System Info (optional)

Github Action, v0.29

### Issues details

I specified the model to use in the config file `.pr_agent.toml` like this:

```
[config]
model = "gpt-4.1-nano"

[pr_description]
generate_ai_title = true
```

I'm using the github action:

```
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@v0.29
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

But the logs show that a different model is being used.

```
{"text": "Relevant configs\n", "record": {"elapsed": {"repr": "0:00:04.793819", "seconds": 4.793819}, "exception": null, "extra": {"artifact": {"pr_description": {"publish_labels": false, "add_original_user_description": true, "generate_ai_title": false, "use_bullet_points": true, "extra_instructions": "", "enable_pr_type": true, "final_update_message": false, "enable_help_text": false, "enable_help_comment": true, "publish_description_as_comment": false, "publish_description_as_comment_persistent": true, "enable_semantic_files_types": true, "collapsible_file_list": "adaptive", "collapsible_file_list_threshold": 6, "inline_file_summary": false, "use_description_markers": false, "include_generated_by_header": true, "enable_large_pr_handling": true, "max_ai_calls": 4, "async_ai_calls": true}, "config": {"enable_custom_labels": false, "model": "o4-mini", "fallback_models": ["gpt-4.1"], "git_provider": "github", "publish_output": true, "publish_output_progress": true, "verbosity_level": 0, "use_extra_bad_extensions": false, "log_level": "DEBUG", "use_wiki_settings_file": true, "use_repo_settings_file": true, "use_global_settings_file": true, "disable_auto_feedback": false, "ai_timeout": 120, "skip_keys": [], "custom_reasoning_model": false, "response_language": "en-US", "max_description_tokens": 500, "max_commits_tokens": 500, "max_model_tokens": 32000, "custom_model_max_tokens": -1, "model_token_count_estimate_factor": 0.3, "patch_extension_skip_types": [".md", ".txt"], "allow_dynamic_context": true, "max_extra_lines_before_dynamic_context": 10, "patch_extra_lines_before": 5, "patch_extra_lines_after": 1, "secret_provider": "", "cli_mode": false, "ai_disclaimer_title": "", "ai_disclaimer": "", "output_relevant_configurations": false, "large_patch_policy": "clip", "duplicate_prompt_examples": false, "seed": -1, "temperature": 0.2, "ignore_pr_title": ["^\\[Auto\\]", "^Auto"], "ignore_pr_target_branches": [], "ignore_pr_source_branches": [], "ignore_pr_labels": [], "ignore_pr_authors": [], "ignore_repositories": [], "is_auto_command": true, "enable_ai_metadata": false, "reasoning_effort": "medium", "enable_auto_approval": false, "auto_approve_for_low_review_effort": -1, "auto_approve_for_no_suggestions": false, "enable_claude_extended_thinking": false, "extended_thinking_budget_tokens": 2048, "extended_thinking_max_output_tokens": 4096}}}, "file": {"name": "pr_description.py", "path": "/app/pr_agent/tools/pr_description.py"}, "function": "run", "level": {"icon": "🐞", "name": "DEBUG", "no": 10}, "line": 98, "message": "Relevant configs", "module": "pr_description", "name": "pr_agent.tools.pr_description", "process": {"id": 7, "name": "MainProcess"}, "thread": {"id": 140613817809792, "name": "MainThread"}, "time": {"repr": "2025-05-20 00:52:16.617952+00:00", "timestamp": 1747702336.617952}}}
{"text": "Generating prediction with o4-mini\n", "record": {"elapsed": {"repr": "0:00:04.799592", "seconds": 4.799592}, "exception": null, "extra": {}, "file": {"name": "pr_processing.py", "path": "/app/pr_agent/algo/pr_processing.py"}, "function": "retry_with_fallback_models", "level": {"icon": "🐞", "name": "DEBUG", "no": 10}, "line": 326, "message": "Generating prediction with o4-mini", "module": "pr_processing", "name": "pr_agent.algo.pr_processing", "process": {"id": 7, "name": "MainProcess"}, "thread": {"id": 140613817809792, "name": "MainThread"}, "time": {"repr": "2025-05-20 00:52:16.623725+00:00", "timestamp": 1747702336.623725}}}
```

Does my config file look correct? Why isn't `gpt-4.1-nano` used in the generation? Thank you.
