### ISSUE TITLE
Would it be appropriate to add a failing test case to try_fix_yaml that requires multiple fallbacks to be applied together?

### ISSUE THREAD

**Issue by jwsong98** [qodo-ai/pr-agent#1804]
### Git provider (optional)

None

### Issues details

I’m currently writing unit tests for the try_fix_yaml function and noticed something I’d like to ask about.

It seems that try_fix_yaml applies each fallback using a deep copy of the original input every time, which means that cases requiring multiple fallbacks in sequence cannot be fixed. For example, in the following case, the YAML can only be corrected if two fallbacks are applied together:
```yaml
code_suggestions:
- relevant_file: |
    tsconfig.json
  existing_code: |
    {
+     "key1": "value1",
      "key2": {
        "subkey": "value"
      }
  }
```

This example combines two issues:
1. An inconsistent indent level within a block scalar (YAML formatting), and
2. A + sign indicating a diff-style line, as commonly generated by AI tools.

From my understanding, this kind of situation might not occur often, or maybe there’s another reason behind this design. Since I’m still learning how PR Agent works, I’d appreciate your insights.

Would it make sense to prepare for such cases in the future? If so, I’m considering writing a test case to simulate this scenario.
